:recycle: Deleted non-functional code
srm-kzilla/og-image pull request #4
Opened 2020-10-30 15:34 UTC by saa27

Made required changes in the parser file

## Changes
- Removed unwanted variables (images, height, width)
- Removed functions associated with these variables
- Added a new required variable (template)

2020-10-30 19:15 UTC, ruddha2001 requested changes

2020-10-30 19:15 UTC, ruddha2001 commented on api/_lib/parser.ts
> -import { IncomingMessage } from 'http';
@saa27 Please use `ESLint` for formatting the code.

You need the following extension (make sure you have the prerequisite mentioned in the document) for the same:
- https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint (This also has instructions on how to set up your formatter)

2020-10-31 05:00 UTC, saa27 commented
Did the requested changes. Please have a look! @ruddha2001

2020-10-31 05:02 UTC, ruddha2001 approved these changes

2020-10-31 05:03 UTC, ruddha2001 commented
@saa27 Looks good to me!

2020-10-31 05:04 UTC, merged